apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  # namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        volumeMounts:
        - name: claim
          mountPath: /usr/share/nginx/html
      volumes:
      - name: claim
        persistentVolumeClaim:
          claimName: claim-200
