apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-300
spec:
  storageClassName: "local-storage" # Empty string must be explicitly set otherwise default StorageClass will be set
  capacity:            # how much
    storage: 300Mi
  accessModes:         # additional params
    - ReadWriteOnce
  hostPath:            # volume type params
    path: "/mnt/data"
    type: DirectoryOrCreate
