apiVersion: apps/v1
kind: Deployment
metadata:
  name: rambo
  labels:
    app: rambo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: rambo
  template:
      metadata:
        labels:
            app: rambo
      spec:
          containers:
          - image: bletvaska/rambo:1
            name: rambo
            volumeMounts:
            - mountPath: /cache
              name: cache-volume
            - mountPath: /usr/share/nginx/html
              name: persistent-volume
          volumes:
          - name: cache-volume
            emptyDir: {}
          - name: persistent-volume
            hostPath:
                path: /tmp/data
                type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rambo
  name: rambo
spec:
  type: NodePort
  nodePort: 33000
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rambo

