apiVersion: v1
kind: Namespace
metadata:
  name: rambo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rambo-1
  name: rambo-1
  namespace: rambo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rambo-1
  template:
    metadata:
      labels:
        app: rambo-1
    spec:
      containers:
      - image: bletvaska/rambo:1
        name: rambo-1

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rambo-1
  name: rambo-1
  namespace: rambo
spec:
  ports:
  - name: www
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rambo-1
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rambo-2
  name: rambo-2
  namespace: rambo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rambo-2
  template:
    metadata:
      labels:
        app: rambo-2
    spec:
      containers:
      - image: bletvaska/rambo:2
        name: rambo-2

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rambo-2
  name: rambo-2
  namespace: rambo
spec:
  ports:
  - name: www
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rambo-2
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: rambo
spec:
  rules:
  - host: www.rambo1.sk
    http:
      paths:
      - backend:
          service:
            name: rambo-1
            port:
              number: 80
        path: /
        pathType: Prefix  # Prefix

  - host: www.paradzina.sk
    http:
      paths:
      - backend:
          service:
            name: rambo-1
            port:
              number: 80
        path: /rambo/1
        pathType: Exact  # Prefix

      - backend:
          service:
            name: rambo-2
            port:
              number: 80
        path: /rambo/2
        pathType: Prefix  # Prefix

      - backend:
          service:
            name: rambo-3
            port:
              number: 80
        path: /rambo/3
        pathType: Prefix  # Prefix
