apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/homepage"
    type: DirectoryOrCreate

