apiVersion: v1
kind: Service
metadata:
  name: rambo
  labels:
    app: rambo
spec:
  type: NodePort
  ports:
  - port: 80
    name: web
    nodePort: 30500
  selector:
    app: rambo

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rambo
spec:
  serviceName: "rambo"
  replicas: 4
  selector:
    matchLabels:
      app: rambo
  template:
    metadata:
      labels:
        app: rambo
    spec:
      containers:
      - name: rambo
        image: bletvaska/rambo:2
        ports:
        - containerPort: 80
          name: rambo
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi

