apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer-cl
  namespace: the-project
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
