# apiVersion: v1
# kind: Namespace
# metadata:
#   name: the-project

# ---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  # namespace: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: secret

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
  # namespace: the-project
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: adminer
  # namespace: the-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer-cl
  # namespace: the-project
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer-lb
  # namespace: the-project
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer-np
  # namespace: the-project
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
    nodePort: 31600
  selector:
    app: adminer
  type: NodePort
