# apiVersion: v1
# kind: Namespace
# metadata:
#   name: adminer-imp
# 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
  namespace: adminer-imp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        version: "10.8"
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          #value: secret
          valueFrom:
            configMapKeyRef:
                name: mariadb
                key: root_password
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
                name: mariadb
                key: database
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
                name: mariadb
                key: user
        - name: MARIADB_PASSWORD
          valueFrom:
            configMapKeyRef:
                name: mariadb
                key: password

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adminer
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer-cl
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer-np
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
  type: NodePort

