apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather
  name: weather
  # namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - image: bletvaska/weather
        name: weather
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: credentials


        # env:
        # - name: WEATHER_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: credentials
        #       key: token

        # env:
        # - name: WEATHER_QUERY
        #   valueFrom:
        #     configMapKeyRef:
        #       name: app-settings
        #       key: query
        # - name: WEATHER_UPDATE_INTERVAL
        #   valueFrom:
        #     configMapKeyRef:
        #       name: app-settings
        #       key: update_interval
