apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-claim
spec:
  storageClassName: "ssd" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:         # params
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 100Mi
        volumeMounts:
        - name: claim
          mountPath: /usr/share/nginx/html
      volumes:
      - name: storage1
        emptyDir:
          sizeLimit: 100Mi
      - name: storage
        hostPath:
          path: /tmp/www
          type: DirectoryOrCreate
      - name: claim
        persistentVolumeClaim:
          claimName: www-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: www
    port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
