apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-100
  # namespace: application
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
