apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-claim
  # namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
  # namespace: wordpress
data:
  MARIADB_DATABASE: wordpress

---

apiVersion: v1
kind: Secret
metadata:
  name: credentials
  # namespace: wordpress
data:
  MARIADB_ROOT_PASSWORD: dG9wLnNlY3JldA==
  MARIADB_USER: d3B1c2Vy
  MARIADB_PASSWORD: ZW5kMzIx

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-db
    tier: backend
    env: prod
    customer: tuke
  name: wp-db
  # namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-db
  template:
    metadata:
      labels:
        app: wp-db
    spec:
      containers:
        - image: mariadb
          name: mariadb
          envFrom:
          - configMapRef:
              name: settings
          - secretRef:
              name: credentials
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: db
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: db-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-db
  name: wp-db
  # namespace: wordpress
spec:
  ports:
    - name: db
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: wp-db
  type: ClusterIP
