apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: adminer
        tier: frontend
        env: dev
    name: adminer
spec:
    replicas: 1
    selector:
        matchLabels:
            app: adminer
    template:
        metadata:
            labels:
                app: adminer
                tier: frontend
                env: dev
        spec:
            containers:
                - image: adminer
                  name: adminer

---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: adminer
    name: wp-adminer
spec:
    type: NodePort
    ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: adminer
