# apiVersion: v1
# kind: Namespace
# metadata:
#   name: wordpress

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-db
    tier: backend
    env: prod
    customer: tuke
  name: wp-db
  # namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        customer: tuke
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: top.secret
        - name: MARIADB_DATABASE
          value: wordpress
        - name: MARIADB_USER
          value: wpuser
        - name: MARIADB_PASSWORD
          value: end321

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-db
  name: wp-db
  # namespace: wordpress
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-app
    tier: frontend
    env: prod
    customer: tuke
  name: wp-app
  # namespace: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wp-db
        - name: WORDPRESS_DB_USER
          value: wpuser
        - name: WORDPRESS_DB_PASSWORD
          value: end321
        - name: WORDPRESS_DB_NAME
          value: wordpress

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-app
  name: wp-app
  # namespace: wordpress
spec:
  ports:
  - name: wordpress
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-adminer
    tier: frontend
    env: dev
  name: wp-adminer
  # namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-adminer
  name: wp-adminer
  # namespace: wordpress
spec:
  ports:
  - name: adminer
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: adminer
  type: NodePort

