apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  namespace: wordpress
type: Opaque

data:
    WORDPRESS_DB_USER: "dXNlcg=="           # user
    WORDPRESS_DB_PASSWORD: "cGFzc3dvcmQ="   # password
