apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  type: NodePort
  ports:
  - port: 9000
    name: api
    nodePort: 30000
  - port: 9001
    name: ui
    nodePort: 30001
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  serviceName: minio
  selector:
    matchLabels:
      app: minio
  replicas: 3
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: minio
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: minio
        image: bitnami/minio
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: ui
      volumeMounts:
      - name: minio-data
        mountPath: /bitnami/minio/data
  volumeClaimTemplates:
  - metadata:
      name: minio-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 100Mi

