apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rambo-1
  name: rambo-1
    #  namespace: rambo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rambo-1
  template:
    metadata:
      labels:
        app: rambo-1
    spec:
      containers:
      - image: bletvaska/rambo:1
        name: rambo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rambo-2
  name: rambo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rambo-2
  template:
    metadata:
      labels:
        app: rambo-2
    spec:
      containers:
      - image: bletvaska/rambo:2
        name: rambo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rambo-3
  name: rambo-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rambo-3
  template:
    metadata:
      labels:
        app: rambo-3
    spec:
      containers:
      - image: bletvaska/rambo:3
        name: rambo

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rambo-1
  name: rambo-1
    #  namespace: rambo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rambo-1

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rambo-2
  name: rambo-2
    #  namespace: rambo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rambo-2

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rambo-3
  name: rambo-3
    #  namespace: rambo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rambo-3

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rambo
  namespace: rambo
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: rambo-1
            port:
              number: 80
        path: /rambo/1
        pathType: Exact
      - backend:
          service:
            name: rambo-2
            port:
              number: 80
        path: /rambo/2
        pathType: Exact
      - backend:
          service:
            name: rambo-3
            port:
              number: 80
        path: /rambo/3
        pathType: Exact

