apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer-lb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
  type: LoadBalancer
