apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
    customer: t-sys
    tier: backend
    env: dev
    version: 10.7.3
    region: europe
  name: db

spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        type: pod
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: secret

