apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
    customer: t-sys
    env: dev
    region: europe
    tier: backend
    version: 10.7.3
  name: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
