apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: secret
  - image: bletvaska/rambo:5
    name: rambo
  - image: adminer
    name: adminer
