apiVersion: v1
kind: Namespace
metadata:
  name: storage

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
  namespace: storage
data:
  MINIO_DEFAULT_BUCKETS: pictures,videos,music,books

---

apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: storage
data:
  MINIO_ROOT_USER: amFub3Npaw==  # echo -n "janosik" | base64
  MINIO_ROOT_PASSWORD: b3Bhc3Rvay52eWJpamFueQ==  # echo -n "opastok.vybijany" | base64

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - image: bitnami/minio
        name: minio
        envFrom:
        - configMapRef:
            name: settings
        - secretRef:
            name: credentials

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-cl
  namespace: storage
spec:
  ports:
  - name: www
    port: 9001
    protocol: TCP
    targetPort: 9001
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-np
  namespace: storage
spec:
  ports:
  - name: www
    port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 32000
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 32001
  selector:
    app: minio
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-lb
  namespace: storage
spec:
  ports:
  - name: www
    port: 9001
    protocol: TCP
    targetPort: 9001
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: storage
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: minio-cl
            port:
              number: 9001
        path: /
        pathType: Prefix  # Prefix
