apiVersion: v1
kind: Namespace
metadata:
  name: application

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
  namespace: application
data:
  query: bratislava,sk
  units: metric
  update_interval: "20"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: secrets

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: application
spec:
  ports:
  - name: www
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
