apiVersion: v1
kind: Namespace
metadata:
  name: minio

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
  namespace: minio
data:
  MINIO_ROOT_USER: janosik
  MINIO_ROOT_PASSWORD: valaska123
  MINIO_DEFAULT_BUCKETS: pictures,videos,music,docs

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - image: bitnami/minio
        name: minio
        envFrom:
        - configMapRef:
            name: settings

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  ports:
  - name: www
    port: 9001
    protocol: TCP
    targetPort: 9000
  - name: api
    port: 9000
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
  type: LoadBalancer
