apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: storage
type: Opaque

data:
    MINIO_ROOT_USER: "amFub3Npaw=="                 # janosik
    MINIO_ROOT_PASSWORD: "b3Bhc3Rvay52eWJpamFueQ==" # opastok.vybijany
