apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data
spec:
  storageClassName: "local-path"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
    type: DirectoryOrCreate

